---
title: "TidyTuesday_420"
author: "Eva Aggarwal"
format: pdf
editor: visual
---

## Loading Data

```{r}
# Option 2: Read directly from GitHub

daily_accidents <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-04-22/daily_accidents.csv')
daily_accidents_420 <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-04-22/daily_accidents_420.csv')
```

```{r}
library(dplyr)
library(lubridate)
library(ggplot2)

daily_accidents <- daily_accidents |>
  mutate(day_of_year = yday(as.Date(date)))

avg_fatalities_by_day <- daily_accidents |>
  group_by(day_of_year) |>
  summarize(avg_fatalities = mean(fatalities_count, na.rm = TRUE))

ggplot(avg_fatalities_by_day, aes(x = day_of_year, y = avg_fatalities)) +
  geom_line() +
    geom_vline(xintercept = 110, linetype = "dashed", color = "red", size = 1) +
   annotate("text", x = 110, y = max(avg_fatalities_by_day$avg_fatalities) + 5, 
           label = "4/20", color = "red", angle = 90, vjust = -0.5) +
  labs(
    title = "Average Fatalities by Day of the Year",
    x = "Day of the Year",
    y = "Average Fatalities"
  ) +
  theme_minimal()
```
